export const CHAMADO_HISTORY_ACTIONS = [
  'abertura',
  'alteracao_status',
  'atribuicao_tecnico',
  'reatribuicao_tecnico',
  'comentario',
  'anexo',
  'cancelamento',
  'classificacao',
  'execucao_registrada',
  'observacao_material',
  'encerramento',
  'avaliado',
  'aguardando_solicitante',
  'retomada_atendimento',
  'pausa_terceiros',
  'retomada_terceiros',
  'recusa',
  'recusa_servico',
  'cotacao_enviada',
  'cotacao_aprovada',
  'cotacao_recusada',
  'reabertura',
] as const;

export type ChamadoHistoryAction = (typeof CHAMADO_HISTORY_ACTIONS)[number];

export const CHAMADO_HISTORY_ACTION_LABELS: Record<ChamadoHistoryAction, string> = {
  abertura: 'Abertura do Chamado',
  alteracao_status: 'Alteração de Status',
  atribuicao_tecnico: 'Atribuição de Técnico',
  reatribuicao_tecnico: 'Reatribuição de Técnico',
  comentario: 'Comentário Adicionado',
  anexo: 'Anexo Adicionado',
  cancelamento: 'Cancelamento do Chamado',
  classificacao: 'Classificação do Chamado',
  execucao_registrada: 'Execução do Serviço Registrada',
  observacao_material: 'Observação de Material',
  encerramento: 'Encerramento do Chamado',
  avaliado: 'Avaliado',
  aguardando_solicitante: 'Aguardando Solicitante',
  retomada_atendimento: 'Atendimento Retomado',
  pausa_terceiros: 'Pausa — Aguardando Terceiros',
  retomada_terceiros: 'Retomada — Terceiros Resolvido',
  recusa: 'Recusa do Chamado',
  recusa_servico: 'Recusa de Serviço pelo Solicitante',
  cotacao_enviada: 'Cotação Enviada para Aprovação',
  cotacao_aprovada: 'Cotação Aprovada',
  cotacao_recusada: 'Cotação Recusada',
  reabertura: 'Reabertura do Chamado',
};
